*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 29 13:34:23 2021] ***
compiled with version: 7.5.0 on 29 August 2021 13:07:25
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/myenv/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :80 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:35878 (port auto-assigned) fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myenv/
Set PythonHome to /workspace/mbittest/myenv/
Python main interpreter initialized at 0x55f6a5e6f470
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55f6a5e6f470 pid: 1001 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 1001)
spawned uWSGI worker 1 (pid: 1004, cores: 1)
spawned uWSGI http 1 (pid: 1005)
subprocess 1002 exited with code 0
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 1005)
worker 1 buried after 2 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 29 13:47:03 2021] ***
compiled with version: 7.5.0 on 29 August 2021 13:07:25
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/myenv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myenv/
Set PythonHome to /workspace/mbittest/myenv/
Python main interpreter initialized at 0x556793547100
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x556793547100 pid: 1044 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 1044)
spawned uWSGI worker 1 (pid: 1047, cores: 1)
subprocess 1045 exited with code 0
[pid: 1047|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 3264 bytes} [Sun Aug 29 13:47:13 2021] GET / => generated 2279 bytes in 139 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 29 13:49:52 2021] ***
compiled with version: 7.5.0 on 29 August 2021 13:07:25
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/myenv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myenv/
Set PythonHome to /workspace/mbittest/myenv/
Python main interpreter initialized at 0x563bf4b4cff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x563bf4b4cff0 pid: 1129 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 1129)
spawned uWSGI worker 1 (pid: 1132, cores: 1)
subprocess 1130 exited with code 0
[pid: 1132|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 3217 bytes} [Sun Aug 29 13:50:03 2021] GET / => generated 2279 bytes in 228 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 29 14:30:58 2021] ***
compiled with version: 7.5.0 on 29 August 2021 13:07:25
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/myenv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myenv/
Set PythonHome to /workspace/mbittest/myenv/
Python main interpreter initialized at 0x55e9da707ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55e9da707ff0 pid: 1151 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 1151)
spawned uWSGI worker 1 (pid: 1154, cores: 1)
subprocess 1152 exited with code 0
[pid: 1154|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 3263 bytes} [Sun Aug 29 14:31:17 2021] GET / => generated 2279 bytes in 291 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1154|app: 0|req: 2/2] 172.17.0.1 () {58 vars in 3286 bytes} [Sun Aug 29 14:31:27 2021] GET /form/ => generated 36777 bytes in 284 msecs (HTTP/1.1 200) 7 headers in 350 bytes (2 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 29 14:33:59 2021] ***
compiled with version: 7.5.0 on 29 August 2021 13:07:25
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/myenv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myenv/
Set PythonHome to /workspace/mbittest/myenv/
Python main interpreter initialized at 0x556be7194ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x556be7194ff0 pid: 1173 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 1173)
spawned uWSGI worker 1 (pid: 1176, cores: 1)
subprocess 1174 exited with code 0
[pid: 1176|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 3263 bytes} [Sun Aug 29 14:34:07 2021] GET / => generated 2279 bytes in 283 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Aug 29 14:42:39 2021] ***
compiled with version: 7.5.0 on 29 August 2021 13:07:25
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/myenv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/myenv/
Set PythonHome to /workspace/mbittest/myenv/
Python main interpreter initialized at 0x564e28804ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x564e28804ff0 pid: 1195 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 1195)
spawned uWSGI worker 1 (pid: 1198, cores: 1)
subprocess 1196 exited with code 0
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 11, in index
    return render(request, 'main/index.html', context=context)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/loader_tags.py", line 277, in do_extends
    parent_name = parser.compile_filter(bits[1])
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/workspace/mbittest/myenv/lib/python3.7/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''main/base.html' from ''main/base.html'
[pid: 1198|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 3263 bytes} [Sun Aug 29 14:42:49 2021] GET / => generated 136079 bytes in 565 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
[pid: 1198|app: 0|req: 2/2] 172.17.0.1 () {60 vars in 3248 bytes} [Sun Aug 29 14:43:11 2021] GET / => generated 2284 bytes in 49 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1198|app: 0|req: 3/3] 172.17.0.1 () {60 vars in 3248 bytes} [Sun Aug 29 14:43:25 2021] GET / => generated 2238 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1198|app: 0|req: 4/4] 172.17.0.1 () {60 vars in 3248 bytes} [Sun Aug 29 14:48:12 2021] GET / => generated 2238 bytes in 5 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1198|app: 0|req: 5/5] 172.17.0.1 () {58 vars in 3240 bytes} [Sun Aug 29 14:48:14 2021] GET /form/ => generated 36742 bytes in 277 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 1198|app: 0|req: 6/6] 172.17.0.1 () {60 vars in 3248 bytes} [Sun Aug 29 14:50:44 2021] GET / => generated 2238 bytes in 5 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Not Found: /result/2
[pid: 1198|app: 0|req: 7/7] 172.17.0.1 () {56 vars in 3187 bytes} [Sun Aug 29 14:50:50 2021] GET /result/2 => generated 2796 bytes in 8 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
